<?php

namespace App\Repository;

use App\Entity\Apartment;
use App\Entity\BackendUser;
use Doctrine\ORM\EntityRepository;

/**
 * ApartmentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends EntityRepository
{
    /**
     * @param BackendUser $backendUser
     * @return Apartment[]
     */
    public function findAdministeredBy(BackendUser $backendUser)
    {
        $res = [];
        foreach ($backendUser->getBuildings() as $building) {
            $res = array_merge($res, $building->getApartments()->toArray());
        }
        return $res;
    }
}
