<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationSlotRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ApplicationSlotRepository extends EntityRepository
{
}
