<?php

namespace App\Repository;

use App\Entity\ApplicationSlot;
use App\Entity\BackendUser;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationSlotRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ApplicationSlotRepository extends EntityRepository
{
    /**
     * @param BackendUser $backendUser
     * @return ApplicationSlot[]
     */
    public function findAdministeredBy(BackendUser $backendUser)
    {
        $res = [];
        foreach ($backendUser->getBuildings() as $building) {
            foreach ($building->getApartments() as $apartment) {
                $res = array_merge($res, $apartment->getApplicationSlots()->toArray());
            }
        }
        return $res;
    }
}
